//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_CORNER                      133
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define IDB_LAWN                        166
#define IDB_BOX                         167
#define IDB_PITOL1                      170
#define IDB_PISTOL1                     170
#define IDB_BULLET                      171
#define IDB_BITMAP3                     172
#define IDB_CURSOR                      172
#define IDB_PLAYER1                     173
#define IDB_PLAYER2                     174
#define IDB_PLAYER3                     175
#define IDB_PLAYER4                     176
#define IDB_PLAYER5                     177
#define IDB_PLAYER6                     178
#define IDB_PLAYER7                     179
#define IDB_PLAYER8                     180
#define IDB_BOXBREAK                    182
#define IDB_ENEMY1                      183
#define IDB_RIP                         184
#define IDB_MachineGun                  185
#define IDB_ENEMY2                      186
#define IDB_ENEMY3                      187
#define IDB_BITMAP2                     189
#define IDB_ShotGun                     189
#define IDB_PLAYER9                     190
#define IDB_PLAYER10                    191
#define IDB_PLAYER11                    192
#define IDB_PLAYER12                    193
#define IDB_PLAYER13                    194
#define IDB_PLAYER14                    195
#define IDB_PLAYER15                    196
#define IDB_PLAYER16                    197
#define IDB_PLAYER17                    198
#define IDB_PLAYER18                    199
#define IDB_PLAYER19                    200
#define IDB_PLAYER20                    201
#define IDB_PLAYER21                    202
#define IDB_PLAYER22                    203
#define IDB_PLAYER23                    204
#define IDB_PLAYER24                    205
#define IDB_PLAYER_MACHINEGUN2          207
#define IDB_PLAYER_MACHINEGUN3          208
#define IDB_PLAYER_MACHINEGUN4          209
#define IDB_PLAYER_MACHINEGUN5          210
#define IDB_PLAYER_MACHINEGUN6          211
#define IDB_PLAYER_MACHINEGUN7          212
#define IDB_PLAYER_MACHINEGUN8          213
#define IDB_PLAYER_MACHINEGUN9          214
#define IDB_PLAYER_MACHINEGUN10         215
#define IDB_PLAYER_MACHINEGUN11         216
#define IDB_PLAYER_MACHINEGUN12         217
#define IDB_PLAYER_MACHINEGUN13         218
#define IDB_PLAYER_MACHINEGUN14         219
#define IDB_PLAYER_MACHINEGUN15         220
#define IDB_PLAYER_MACHINEGUN16         221
#define IDB_PLAYER_MACHINEGUN17         222
#define IDB_PLAYER_MACHINEGUN18         223
#define IDB_PLAYER_MACHINEGUN19         224
#define IDB_PLAYER_MACHINEGUN20         225
#define IDB_PLAYER_MACHINEGUN21         226
#define IDB_PLAYER_MACHINEGUN22         227
#define IDB_PLAYER_MACHINEGUN23         228
#define IDB_PLAYER_MACHINEGUN24         229
#define IDB_HealthBar1                  230
#define IDB_HealthBar2                  231
#define IDB_HealthBar3                  232
#define IDB_HealthBar4                  233
#define IDB_HealthBar5                  234
#define IDB_HealthBar6                  235
#define IDB_HealthBar7                  236
#define IDB_HealthBar8                  237
#define IDB_HealthBar9                  238
#define IDB_HealthBar10                 239
#define IDB_HealthBar11                 240
#define IDB_BULLET_IMG                  241
#define IDB_LOGO                        242
#define IDB_WIN                         243
#define IDB_LOSE                        244
#define IDB_ItemUI1                     245
#define IDB_ItemUI2                     246
#define IDB_ItemUI3                     247
#define IDB_ItemUI1_2                   248
#define IDB_ItemUI2_2                   249
#define IDB_BULLET2                     250
#define IDB_BITMAP4                     251
#define IDB_BULLET3                     251
#define IDB_PNG1                        253
#define IDB_BITMAP5                     255
#define IDB_Bandage                     255
#define IDB_PLAYER_MACHINEGUN1          300
#define IDB_PLAYER_SHOTGUN1             301
#define IDB_PLAYER_SHOTGUN2             302
#define IDB_PLAYER_SHOTGUN3             303
#define IDB_PLAYER_SHOTGUN4             304
#define IDB_PLAYER_SHOTGUN5             305
#define IDB_PLAYER_SHOTGUN6             306
#define IDB_PLAYER_SHOTGUN7             307
#define IDB_PLAYER_SHOTGUN8             308
#define IDB_PLAYER_SHOTGUN9             309
#define IDB_PLAYER_SHOTGUN10            310
#define IDB_PLAYER_SHOTGUN11            311
#define IDB_PLAYER_SHOTGUN12            312
#define IDB_PLAYER_SHOTGUN13            313
#define IDB_PLAYER_SHOTGUN14            314
#define IDB_PLAYER_SHOTGUN15            315
#define IDB_PLAYER_SHOTGUN16            316
#define IDB_PLAYER_SHOTGUN17            317
#define IDB_PLAYER_SHOTGUN18            318
#define IDB_PLAYER_SHOTGUN19            319
#define IDB_PLAYER_SHOTGUN20            320
#define IDB_PLAYER_SHOTGUN21            321
#define IDB_PLAYER_SHOTGUN22            322
#define IDB_PLAYER_SHOTGUN23            323
#define IDB_PLAYER_SHOTGUN24            324
#define IDB_PLAYER_PISTOL1              325
#define IDB_PLAYER_PISTOL2              326
#define IDB_PLAYER_PISTOL3              327
#define IDB_PLAYER_PISTOL4              328
#define IDB_PLAYER_PISTOL5              329
#define IDB_PLAYER_PISTOL6              330
#define IDB_PLAYER_PISTOL7              331
#define IDB_PLAYER_PISTOL8              332
#define IDB_PLAYER_PISTOL9              333
#define IDB_PLAYER_PISTOL10             334
#define IDB_PLAYER_PISTOL11             335
#define IDB_PLAYER_PISTOL12             336
#define IDB_PLAYER_PISTOL13             337
#define IDB_PLAYER_PISTOL14             338
#define IDB_PLAYER_PISTOL15             339
#define IDB_PLAYER_PISTOL16             340
#define IDB_PLAYER_PISTOL17             341
#define IDB_PLAYER_PISTOL18             342
#define IDB_PLAYER_PISTOL19             343
#define IDB_PLAYER_PISTOL20             344
#define IDB_PLAYER_PISTOL21             345
#define IDB_PLAYER_PISTOL22             346
#define IDB_PLAYER_PISTOL23             347
#define IDB_PLAYER_PISTOL24             348
#define IDB_RELOADING1                  349
#define IDB_RELOADING2                  350
#define IDB_RELOADING3                  351
#define IDB_RELOADING4                  352
#define IDB_BALL2                       353
#define IDB_BLOOD                       354
#define IDB_ICON                        355
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
