//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_LOADING                     156
#define IDB_MAP1                        157
#define IDB_MAP2                        158
#define IDB_MAP3                        159
#define IDB_MAP4                        160
#define IDB_MAP5                        161
#define IDB_MAP6                        162
#define IDB_MAP7                        163
#define IDB_MAP8                        164
#define IDB_MAP9                        165
#define IDB_LAWN                        166
#define IDB_BOX                         167
#define IDB_PITOL1                      170
#define IDB_PISTOL1                     170
#define IDB_BULLET                      171
#define IDB_BITMAP3                     172
#define IDB_CURSOR                      172
#define IDB_PLAYER1                     173
#define IDB_PLAYER2                     174
#define IDB_PLAYER3                     175
#define IDB_PLAYER4                     176
#define IDB_PLAYER5                     177
#define IDB_PLAYER6                     178
#define IDB_PLAYER7                     179
#define IDB_PLAYER8                     180
#define IDB_BOXBREAK                    182
#define IDB_ENEMY1                      183
#define IDB_RIP                         184
#define IDB_MachineGun                  185
#define IDB_ENEMY2                      186
#define IDB_ENEMY3                      187
#define IDB_BITMAP2                     189
#define IDB_ShotGun                     189
#define IDB_PLAYER9                     190
#define IDB_PLAYER10                    191
#define IDB_PLAYER11                    192
#define IDB_PLAYER12                    193
#define IDB_PLAYER13                    194
#define IDB_PLAYER14                    195
#define IDB_PLAYER15                    196
#define IDB_PLAYER16                    197
#define IDB_PLAYER17                    198
#define IDB_PLAYER18                    199
#define IDB_PLAYER19                    200
#define IDB_PLAYER20                    201
#define IDB_PLAYER21                    202
#define IDB_PLAYER22                    203
#define IDB_PLAYER23                    204
#define IDB_PLAYER24                    205
#define IDB_PLAYER_MACHINEGUN1                     206
#define IDB_PLAYER_MACHINEGUN2                     207
#define IDB_PLAYER_MACHINEGUN3                     208
#define IDB_PLAYER_MACHINEGUN4                     209
#define IDB_PLAYER_MACHINEGUN5                     210
#define IDB_PLAYER_MACHINEGUN6                     211
#define IDB_PLAYER_MACHINEGUN7                     212
#define IDB_PLAYER_MACHINEGUN8                     213
#define IDB_PLAYER_MACHINEGUN9                     214
#define IDB_PLAYER_MACHINEGUN10                    215
#define IDB_PLAYER_MACHINEGUN11                    216
#define IDB_PLAYER_MACHINEGUN12                    217
#define IDB_PLAYER_MACHINEGUN13                    218
#define IDB_PLAYER_MACHINEGUN14                    219
#define IDB_PLAYER_MACHINEGUN15                    220
#define IDB_PLAYER_MACHINEGUN16                    221
#define IDB_PLAYER_MACHINEGUN17                    222
#define IDB_PLAYER_MACHINEGUN18                    223
#define IDB_PLAYER_MACHINEGUN19                    224
#define IDB_PLAYER_MACHINEGUN20                    225
#define IDB_PLAYER_MACHINEGUN21                    226
#define IDB_PLAYER_MACHINEGUN22                    227
#define IDB_PLAYER_MACHINEGUN23                    228
#define IDB_PLAYER_MACHINEGUN24                    229
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
